"""Generate Rust DOP853 coefficients from E. Hairer's original Fortran source.

Usage:
    curl -sSfL -o dop853.f http://www.unige.ch/~hairer/prog/nonstiff/dop853.f
    python scripts/gen_dop853_coefficients.py dop853.f > crates/physics/src/integrator/dop853_coefficients.rs

The coefficients are copied mechanically (no hand transcription). Arrays use
Hairer's 1-based indices; index 0 and absent entries are zero.
"""

import hashlib
import re
import sys

N = 17  # stages 1..16, index 0 unused


def main(path: str) -> None:
    src = open(path, "rb").read()
    sha = hashlib.sha256(src).hexdigest()
    text = src.decode("ascii")

    # Only the coefficient block of the core integrator DP86CO.
    start = text.index("SUBROUTINE DP86CO")
    end = text.index("DOUBLE PRECISION Y(N)", start)
    block = text[start:end]

    pairs = re.findall(r"([a-z]+ ?\d+)\s*=\s*([-+]?[0-9.]+D[-+]?\d+)", block)
    if not pairs:
        sys.exit("no coefficients found")

    a = [[None] * N for _ in range(N)]
    b = [None] * N
    c = [None] * N
    e = [None] * N
    bhh = [None] * 4
    d = [[None] * N for _ in range(8)]

    seen = set()
    for name, value in pairs:
        name = name.replace(" ", "")
        if name in seen:
            sys.exit(f"duplicate coefficient {name}")
        seen.add(name)
        lit = value.replace("D", "E")
        prefix = re.match(r"[a-z]+", name).group(0)
        digits = name[len(prefix):]
        if prefix == "a":
            # a{i}{j} with j < i <= 16: 2 digits -> i,j single; 3 -> i two-digit, j one;
            # 4 -> both two-digit.
            split = {2: 1, 3: 2, 4: 2}[len(digits)]
            i, j = int(digits[:split]), int(digits[split:])
            assert j < i, name
            a[i][j] = lit
        elif prefix == "b":
            b[int(digits)] = lit
        elif prefix == "c":
            c[int(digits)] = lit
        elif prefix == "er":
            e[int(digits)] = lit
        elif prefix == "bhh":
            bhh[int(digits)] = lit
        elif prefix == "d":
            d[int(digits[0])][int(digits[1:])] = lit
        else:
            sys.exit(f"unknown coefficient {name}")

    # Stages 12 and 13 are evaluated at x + h in Hairer's code (XPH); they have no
    # c parameter in the source.
    assert c[12] is None and c[13] is None
    c[12] = "1.0"
    c[13] = "1.0"

    def fmt(v):
        return "0.0" if v is None else v

    def vec(xs):
        return "[" + ", ".join(fmt(x) for x in xs) + "]"

    out = []
    out.append("// @generated by scripts/gen_dop853_coefficients.py -- do not edit by hand.")
    out.append("//")
    out.append("// Source: http://www.unige.ch/~hairer/prog/nonstiff/dop853.f")
    out.append(f"// SHA-256 of source: {sha}")
    out.append("// Dormand-Prince 8(5,3) with 7th-order dense output, as in")
    out.append("// Hairer, Norsett, Wanner, Solving ODEs I (2nd ed., 1993), Section II.10.")
    out.append("// Indices are Hairer's (1-based); index 0 and absent entries are zero.")
    out.append("")
    out.append("#![allow(clippy::excessive_precision, clippy::unreadable_literal)]")
    out.append("")
    out.append(f"pub const C: [f64; {N}] = {vec(c)};")
    out.append(f"pub const B: [f64; {N}] = {vec(b)};")
    out.append("/// Coefficients of the 5th-order error estimator (Hairer's `er`).")
    out.append(f"pub const E: [f64; {N}] = {vec(e)};")
    out.append("/// Coefficients of the 3rd-order error estimator.")
    out.append(f"pub const BHH: [f64; 4] = {vec(bhh)};")
    out.append(f"pub const A: [[f64; {N}]; {N}] = [")
    for row in a:
        out.append(f"    {vec(row)},")
    out.append("];")
    out.append("/// Dense-output coefficients; rows 4..=7 are used.")
    out.append(f"pub const D: [[f64; {N}]; 8] = [")
    for row in d:
        out.append(f"    {vec(row)},")
    out.append("];")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
